### ISSUE TITLE
Status: No Status showing as text "No Status" rather than "blank field"

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#340]
### Reproduction steps

Select a Parcel
Status drop down menu
Select "No Status"
Status shows as "No Status"

### Expected behaviour

Select a Parcel
Status drop down menu
Select "No Status"
Status shows as "blank field"

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
Plan:
* change "No Status" in the `status_order` table in the DB to be ""
* catch empty string in the logic that builds the Statuses menu and display as "No Status"
* change Last Status filter logic so that "None" matches "" as well as `null`
* update seed data to replace "No Status" by ""

**Comment by stonelink** [comment]
## QA Steps

In the parcels table:
- expand the table to view a large number of parcels (~100)
- check that there are no parcels where the Last Status column has "No Status" or "None"
- there should be some parcels where the Last Status column is empty
- open a few of the parcels with empty Last Status
- for some parcels, in the parcel modal you should see the Event/Status change table is empty
- for other parcels, in the parcel modal you should see the Event/Status change table has a few rows with different status, with the topmost row (most recent) indicating that the status was reset to empty

- Select a small number of parcels, whose statuses are not empty
- In the Statuses droplist, select "No Status"
- Verify that for those parcels the Last Status in the table is now empty, and in the parcel modal the topmost row of the Event/Status change table indicates the status being reset to empty

In the Last Status droplist:
- start with nothing selected (i.e. all non-deleted parcels are visible)
- tick "No Status"
- verify that the parcels in the table have been filtered to only show those with empty Last Status

**Comment by stonelink** [comment]
QA Passed on Safari and Chrome

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
