### ISSUE TITLE
Remove Status when Generating Map

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#373]
### Reproduction steps

When I 
Select a few Parcels
Actions
Generate Map
Download Map

It creates a status that says Map Generated

### Expected behaviour

This action should not generate a status, because you lose track of the parcel's place in the chain. A map might be generated at any stage in the life cycle of the parcel, but we don't want to lose the information of whether that parcel has been called and confirmed or confirmed or packed etc.
Hope that makes sense.

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
This ticket involves:
* changing the action modal logic to accept there being no status change
* removing "Map Generated" from the list of valid statuses in the DB
* changing the database seed logic to not include "Map Generated"
* regenerate the seed data

**Comment by stonelink** [comment]
## QA Steps

On the Parcels page:
- select a few parcels that have a range of statuses (include "Called and Confirmed" and "Out for Delivery" at least)
- under Actions, click Generate Map
- -> verify that a map tab opens as expected
- -> verify that none of the selected parcels had had their status changed

- open the Last Status droplist filter
- -> verify that "Map Generated" (or similar) is not in the list

- open the Statuses menu
- -> verify that "Map Generated" (or similar) is not in the list

**Comment by stonelink** [comment]
QA Passed on Safari and Chrome

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
