### ISSUE TITLE
Parcels table - remove scrollable table within a page - it's easy to miss Parcels on bottom of table 

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#376]
### Describe the solution / feature you'd like

On the parcels table, I think it would be better to remove the scrollable table of Parcel's on the page and make it fixed.
It has been reported that it's easy to miss clients on the table when you are scrolling to the bottom of the webpage, but the client table hasn't also scrolled to the bottom of it's list. Especially when you are viewing up to 100 parcels on the page.

**Comment by stonelink** [comment]
## QA steps

* On the Parcels table:
  * ensure the table has 100 rows per page selected
  * set the date range to be long enough to have >100 rows (e.g. 2 months)
  * -> check that:
    * there is a single scrollbar for the viewport
    * there is not a separate scrollbar on the table
    * all the table rows are visible
    * the table footer is in the expected location below the table data

* On the Clients table:
  * do the same tests as above, excluding the date range

* On the Lists table:
  * -> check that:
    * there is a single vertical scrollbar for the viewport
    * there is not a separate vertical scrollbar on the table
    * all the table rows are visible
    * the table footer (with horizontal scrollbar) is in the expected location below the table data

**Comment by stonelink** [comment]
QA Passed on Safari, Chrome

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
