### ISSUE TITLE
Cannot Edit Users Name or Phone Number

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#377]
### Reproduction steps

When I press the edit button on a user, I can only edit email address and role.

### Expected behaviour

When I press the edit button on a user, I would expect to be able to edit the users name and phone number as well as email and role.

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
This is VFB-295

**Comment by dan-langridge** [comment]
Happy that this is complete
