### ISSUE TITLE
Postcode Search - can't search for multiple postcodes separated by comma

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#391]
### Reproduction steps

When I enter the postcode search box field on the parcels page
and enter
E1, CB
it shows There are no records to display

### Expected behaviour

When i enter multiple postcodes (partial or full) separated by a comma, it would ideally show both or multiple postcodes

e.g. search E1 3AB, E2 7YT - it would show both of those postcodes
or
search E3, E4, E5 - it would show all postcodes in E3, E4, E5

This is an important feature for us, for example for the delivery manager to filter by certain postcodes to assign them to a driver

It would also be helpful to have this on the name search as well - both on the Parcels and Clients page
e.g.
Search name: Dan, John
would show all the Dan's and all the Johns

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
## Spec
* All the `TextFilter` components will treat `,` as a delimiting character - so not just postcode and name, this would apply to Phone number, Voucher, Family size etc. (I can't see a reason for those filters to not support a delimiter)
* When applying text in the input as a filter:
  * divide the string into an array of substrings, delimited by `,`
  * trim whitespace from the start and end of each substring
  * remove any empty substrings from the list
  * apply an 'or' in the DB query to check for a match to any of the substrings

**Comment by stonelink** [comment]
The filters that have had this functionality added are:
- postcode
- full name
- family size
- phone number
- voucher

All of the above appear on the Parcels table; all except Voucher are also on the Clients table. 
Note that the family size filter has only been added to Clients table as part of this ticket.

Note that each filter still has the special cases that it used to support:
- most match '-' with a deleted client
- in postcode filter, 'nfa' matches clients with no address
- in family filter, numbers are the main expectation, any substring of "single" matches Singles, any substring of "family of" matches 2 or more
- in voucher filter, '?' matches no voucher

**Comment by stonelink** [comment]
## QA steps
- test each of the filters listed in the previous comment (individually and in combination), on the Parcels and Clients tables
- for each filter:
  - test that the simple behaviour still works (i.e., a simple string with no commas)
  - test that a few values separated by commas works as expected - i.e., if you enter in the one of the filters a few strings with commas between them, then any parcel that matches any one of those strings should appear in the table
  - check that whitespace before or after the commas is ignored
  - check that some of the special cases that are listed in the previous comment work, including when in a list (e.g., "SW8, nfa" in the postcodes filter makes the table contain parcels where the postcode contains "SW8" or the client has no fixed address)

**Comment by ebinezer04** [comment]
QA done 14/08
All looks good to me

**Comment by dan-langridge** [comment]
Done
