### ISSUE TITLE
Shipping label quantity entry box should be selected automatically when the window pops up so you can type quantity without having to select the box first

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#392]
### Reproduction steps

When I:
- Select a parcel
- Download Shipping Label
- The quantity box is not selected and I have to click in the box to enter a number
- I then can't press the return/enter key on the keyboard to submit and download the label. 
This would save a lot of time

### Expected behaviour

When I:
- Select a parcel
- Download Shipping Label
- The quantity box should be selected automatically when the window pops up so you can type quantity without having to select the box first
- When i hit the return/enter key on the keyboard, this should submit and download the label 

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by Stuart-Knowles-SW** [comment]
Progress tracked on: https://softwiretech.atlassian.net/browse/VFB-308

**Comment by dan-langridge** [comment]
Done
