### ISSUE TITLE
Would save time to be able to press return for submit all green buttons (eg after inputting number of shipping labels to then download pdf, after entering name for driver overview to then download pdf

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#393]
### Reproduction steps

When a pop-up appear son screen with a submit button (download shipping labels, lists, driver overview), I can't use the return/enter key to hit submit, i have to use the mouse

### Expected behaviour

Would save time to be able to press return for submit all green buttons (eg after inputting number of shipping labels to then download pdf, after entering name for driver overview to then download pdf

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
See also https://softwiretech.atlassian.net/browse/VFB-101

**Comment by Jessica-Al** [comment]
@dan-langridge Hi dan, your comment here refers only to the action modals appearing when selecting a dropdown action from the parcels page. Just wanted to check if there are any other modals where you would like this kind of change to be applied?

**Comment by dan-langridge** [comment]
Hey! I think any modal that has a submit button would be great to press Enter. Any action that can be cancelled with an X button could be escape.I think only applicable to pop up modals, not client or parcel forms I would imagine?On 1 Aug 2024, at 12:11, Jessica-Al ***@***.***> wrote:﻿
@dan-langridge Hi dan, you're comment here refers only to the action modals appearing when selecting a dropdown action from the parcels page. Just wanted to check if there are any other modals where you would like this kind of change to be applied?

**Comment by stonelink** [comment]
This is under https://softwiretech.atlassian.net/browse/VFB-101

**Comment by dan-langridge** [comment]
Done
