### ISSUE TITLE
Parcel date range FROM & TO - allow FROM to choose a date in the future

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#394]
### Reproduction steps

“From” date range doesn’t let you select a future date from the drop down calendar without first changing the “to” date to that future date. 

### Expected behaviour

When i choose the FROM picker, I want to set a date in the future, and then open TO to choose either the same date as FROM or a date father in the future. 
Currently I need to work backwards, starting with TO and then going FROM, which is counterintuitive.

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
## Spec thoughts

`DateRangeInputs.tsx` is currently designed as follows:
* the datepickers won't allow disallow selection of dates that would be result in an invalid date range; that is:
  * the 'from' datepicker won't allow selection of dates later than the current 'to' value, and 
  * the 'to' datepicker won't allow selection of dates earlier than the current 'from' value
* the user can type a date that results in an invalid date range
  * this results in the red validation highlight shown below (where the 'From' date has just been typed manually
  * ![Image](https://github.com/user-attachments/assets/f07a4908-4656-4680-8be1-353d2dc76393)

Suggested spec:
* remove restriction from the datepickers (other than the "resonable min date" of 1/1/2020 that's already in the code)
* if the values in the 'from' and 'to' boxes are not a valid date range after a datepicker is used, then the validation highlight(s) should appear in the same way as if the date was entered manually
* the date range values of the filter (i.e., that cause the parcels table rows to change) are only saved if the range is valid

**Comment by stonelink** [comment]
The component `DateRangeInputs.tsx` should have tests, including:
- if initial range is blank there is no error state
- if initial range is set there is no error state 
- if the `from` value is set to a date earlier than or equal to the `to` date then there is no error state and the date range is applied
  - tests for datepicker & keyboard input
- if the `to` value is set to a date later than or equal to the `from` date then there is no error state and the date range is applied
  - tests for datepicker & keyboard input
- if the `from` value is set to a date later than the `to` date then the `to` value changes to match the `from` value and the date range is applied
  - tests for datepicker & keyboard input
- if the `to` value is set to a date earlier than the `from` date then the `from` value changes to match the `to` value and the date range is applied
  - tests for datepicker & keyboard input
- if the controls are in error state and the dates are changed to be valid then the error state is removed and the date range is applied
  - tests for datepicker & keyboard input
  - if either the `to` or `from` value is before 1/1/2020, then there is an error state and the date range is not applied
  - tests for datepicker & keyboard input
  - note that this needs to verify that the values set are as per the controls' current values, not the previous props values

UPDATED to match VFB-320 fixes

**Comment by stonelink** [comment]
QA steps are as per the component test steps written in the above comment.

**Comment by SoftJoelWire** [comment]
QA question:
The first bullet point states that an initial range which is empty should not enter the error state. I am not sure how to test this as I can't find a way for the _initial_ state to be empty. upon deleting both dates in the range, the error state _**is**_ entered so I assume that empty states are only valid when they are the initial one. Is this as expected?

**Comment by SoftJoelWire** [comment]
QA:
other than that looks good!

**Comment by stonelink** [comment]
Thank you @SoftJoelWire :) 
The first bullet point about the empty initial state is just for the automated tests that I'll write once I can get into Jest - it's a test for the date range component in case someone wants to use it in a different way.

**Comment by dan-langridge** [comment]
Happy that this is done
