### ISSUE TITLE
"Last Status" & "Packing Slot" filter buttons are too hidden - move to the main page (not in "More")

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#396]
### Describe the solution / feature you'd like

Filtering by status and packing slot are well used features that should be moved to the main page and not hidden in 'more' to save users time. Can we move them next to the "Method" filter?

**Comment by stonelink** [comment]
## QA steps

Open the Parcels page in the following browsers and verify that beside the _Method_ filter, there are filters for _Packing Slot_ and _Last Status_, which work as expected:
- Chrome
- Safari
- Edge

**Comment by stonelink** [comment]
QA passed on Safari, Chrome, Edge

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
