### ISSUE TITLE
Cosmetic Changes to Shopping List

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#454]
### Describe the solution / feature you'd like

See attached PDF

[ShoppingList_2024_08_02_11_12_52.pdf](https://github.com/user-attachments/files/16469269/ShoppingList_2024_08_02_11_12_52.pdf)

**Comment by Stuart-Knowles-SW** [comment]
Tracked on Jira as [VFB-325](https://softwiretech.atlassian.net/browse/VFB-325)

**Comment by dan-langridge** [comment]
Happy that this is complete
