### ISSUE TITLE
Info page ignoring paragraph break

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#456]
### Reproduction steps

On the Info page, When I try and create a new paragraph break in the text box, it is ignored when i press save.

### Expected behaviour

I would like to be able to use paragraphs in the text box

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by dan-langridge** [comment]
<img width="969" alt="Screenshot 2024-08-02 at 16 09 31" src="https://github.com/user-attachments/assets/c0694e19-e55f-4ad5-8dba-e477beb3e1b6">
<img width="517" alt="Screenshot 2024-08-02 at 16 09 36" src="https://github.com/user-attachments/assets/58287fe7-e603-4caf-a92c-65a757d0b719">

**Comment by rjesson-softwire** [comment]
QA steps: add a wiki item which contains paragraph breaks. Check when saved, the paragraph breaks are shown.

**Comment by LeaHe188** [comment]
QA done!

**Comment by dan-langridge** [comment]
Happy that this works
