### ISSUE TITLE
Driver Overview not showing most recent number of labels created, instead showing first time labels

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#458]
### Reproduction steps

Parcel
Print Shipping Labels (2 labels)
Print Driver Overview (shows 2 labels)
Print Shipping Labels AGAIN (do 4 labels)
Print Driver Overview (still shows 2)

### Expected behaviour

Driver Overview should show the most recent shipping labels created, however it is currently showing the first time shipping labels are created.

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by Stuart-Knowles-SW** [comment]
Also tracked in [VFB-341](https://softwiretech.atlassian.net/browse/VFB-341)

**Comment by dan-langridge** [comment]
Happy that this is complete
