### ISSUE TITLE
Logo doesn't work on Safari v13

### ISSUE THREAD

**Issue by stonelink** [VauxhallFoodbank/vauxhall-foodbank#523]
Currently the webapp logo is a .webp file, which is not supported by Safari version 13.x

### Reproduction steps

- Open the webapp on a Mac running Safari 13.x
- Look at the logo in the top left of the navigation bar
- Note that the image looks broken / doesn't render

### Expected behaviour

The logo should appear in the same way as more modern browsers

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
## QA results
Tested all actions on the Info page on Chrome latest version & Safari 13.1.2. Safari testing was done on both a real MacBook running MacOS High Sierra and on BrowserStack. Tested both light and dark themes.

**Comment by dan-langridge** [comment]
Happy that this works
