### ISSUE TITLE
Info page doesn't work on Safari v13

### ISSUE THREAD

**Issue by stonelink** [VauxhallFoodbank/vauxhall-foodbank#526]
### Reproduction steps

On Safari 13.1.2, click on the INFO link in the nav bar.

The page loads with `OOPS! crypto.randomUUID is not a function.`

### Expected behaviour

The info page should load as normal, and provide functionality to add/edit/delete including content containing links

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
## QA results
Tested all actions on the Info page on Chrome latest version & Safari 13.1.2. Safari testing was done on both a real MacBook running MacOS High Sierra and on BrowserStack.

**Comment by dan-langridge** [comment]
Happy that this now works
